version: '{branch}-{build}'

environment:
  nodejs_version: "10"
  YARN_GPG: no
  nodejs_version: "10"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache

# used on Ubuntu
stack: node 10

install:
  - cmd: PowerShell.exe "Install-Product node $env:nodejs_version"
  - node --version && yarn --version && python --version
  - sh: sudo apt-get --yes install libx11-dev libxkbfile-dev
  - cmd: yarn
  - sh: yarn

build_script:
  - yarn run rebuild:browser && yarn run rebuild:electron
